# http://sasstools.github.io/make-sass-lint-config/

files:
  include: 'resources/assets/sass/**/*.scss'
  ignore: 'node_modules'
rules:
  # @include @extends 的位置
  empty-line-between-blocks: 0
  mixins-before-declarations: 0
  extends-before-declarations: 0
  extends-before-mixins: 0
  # 縮排
  indentation:
    - 1
    - size: 2
  nesting-depth:
    - 1
    - max-depth: 5
  no-color-keywords: 0
  no-color-literals: 0
  no-mergeable-selectors: 0
  property-sort-order: 
    - 0
    - order: 'smacss'
  class-name-format: 
    - 0
    - convention: hyphenatedlowercase
  force-pseudo-nesting: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  no-transition-all: 0
  quotes: 
    - 1
    - style: double
  # 非標準 prefixes 不提醒
  no-vendor-prefixes:
    - 1
    - ignore-non-standard: true
